Vagrant.configure('2') do |config|
  config.vm.boot_timeout = 900
  (1..3).each do |i|
    config.vm.define "ubuntu#{i}" do |node|
      node.vm.synced_folder '.', '/vagrant', disabled: true
      node.vm.box = 'generic/ubuntu2204'
      node.vm.box_check_update = false
      node.vm.box_version = '4.2.16'
      node.vm.hostname = "keepalive-#{i}"
      node.vm.network 'private_network', ip: "172.16.16.10#{i}"
      node.vm.provider :virtualbox do |v|
        v.name = "keepalive-#{i}"
        v.memory = 2024
        v.cpus = 2
        # disable the usb ports insdie VM
        v.customize ['modifyvm', :id, '--uartmode1', 'disconnected']
      end
    end
  end
  # To set the environment variables inside the vagrant machines
  # config.vm.provision "shell", inline: "> /etc/profile.d/myvars.sh", run: "always"
  # config.vm.provision "shell", inline: "echo 'export TERM=xterm-256color' >> /etc/profile.d/myvars.sh", run: "always"
  config.vm.provision 'shell',
             inline: <<-SHELL
    sudo apt -y update
    SHELL
end
